### ISSUE TITLE
Reduce react/layer-manager component into single API for rendering

### ISSUE THREAD

**Issue by edbrett** [Vizzuality/layer-manager#21]
@sorodrigo @mbarrenechea  @andresgnlez @davidsingal.

At the moment we have 3 methods for rendering the `<Layer />` component inside the `<LayerManager />`: a child function, as children themselves, or passing layersSpec as a prop. It would be nice to have a single method for this as these are not consistent.

See here:
https://github.com/Vizzuality/layer-manager/blob/develop/src/react/layer-manager.js#L35

At the moment the first requires manually sending zIndex in order to make layer stacking function correctly, whereas the other dont. Just one of the issues.

**Comment by davidsingal** [comment]
I agree with you about being consistent and have a solid method to use LayerManager. I don't like to pass Components as a property because we already have children that have been designed for that.

But I think z-index issue is not related to rendering methods. I think it should be a different issue.

**Comment by sorodrigo** [comment]
Yes so right now, the method of passing `<Layer />` as a children injects two props to the layer components: `layerManager` and `zIndex`. But I think I understand what you mean, this is a little inflexible. This was meant to be a default that can be overriden, but maybe it should be removed and only inject the `layerManager` prop. Thoughts?

I think that having both `render prop` and `<Layer /> as children` APIs is unnecessary, they do exactly the same thing.

**Comment by mbarrenechea** [comment]
We have 3 options:
- The one that passes it as a prop should be discarded
- Is the function necessary? As we are passing the layerManager inside the LayerManager component to all the children I feel that we don't need it.
- So.... do we have a winner? The one that is simply children. The first one BTW

**Comment by andresgnlez** [comment]
Why do you need to expose Layers outside the Layermanager? Doesn't make any sense to me. Layer manager manages layers through an array of specs, and that should be the premise. Exposing the Layer outside is unnecessary, IMO.

**Comment by edbrett** [comment]
Agreed I like the flexibility of the children and it is much easier to read in your app what you are doing to each layer.

**Comment by davidsingal** [comment]
At the end LayerManager component is a HOC, we can check other libraries like: https://github.com/clauderic/react-sortable-hoc

**Comment by edbrett** [comment]
solved in #60
