### ISSUE TITLE
Don't make all interface methods required

### ISSUE THREAD

**Issue by sorodrigo** [Vizzuality/layer-manager#24]
I think many of the plugin interface methods should be opt-in. There's no need to validate if a plugin has as required methods `setLayerConfig`, `setParams`, `setDecodeParams`. IMO the LayerManager should check if they exist and if they don't just ignore them.

Thoughts @mbarrenechea @edbrett ?

**Comment by mbarrenechea** [comment]
We have 2 options:
- Leave it as it is
- Do what you are asking for. So we will need to go through the code and put checks every time we use `this.plugin.XXX`. Also, we will need to say to the user that the current `this.plugin.XXX`is not present.

As this is something that we are going to use as a company, and the plugin is going to be something fixed that we consume, I don't think that it is worth it
