### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by davidsingal** [Vizzuality/layer-manager#35]
In order to make it clearer, we still miss:

- [x] What's a plugin?
- [x] How to create and register a plugin.
- [x] Layer Spec schema.
- [x] Contribution guidelines.
- [x] Development instructions.

Bonus:

- [ ] More examples

**Comment by mbarrenechea** [comment]
#37

**Comment by migh** [comment]
Hey, is there a place for docs or just the README?

**Comment by mbarrenechea** [comment]
@migh  https://github.com/Vizzuality/layer-manager/wiki we started working on this. I will close the issue as soon as we finish it
