### ISSUE TITLE
Import and compilation issues working with LayerManager in Rails and Next projects

### ISSUE THREAD

**Issue by davidsingal** [Vizzuality/layer-manager#36]
Sometimes we have some issues importing the library. Furthermore, it is not very consistent and clear to use.

Possible reasons:
* Issues importing as an es module.
* Conflicts with Babel compilation in external projects.
* Conflicts with Uglify using wrong exported files.
* Poor documentation for how to use the library.

**Comment by davidsingal** [comment]
This PR is still on work in progress but it tries to sort out this issues #33.

**Comment by edbrett** [comment]
@davidsingal this is resolved no?
