### ISSUE TITLE
[BUG] onReady regression

### ISSUE THREAD

**Issue by andresgnlez** [Vizzuality/layer-manager#47]
At some point (https://github.com/Vizzuality/layer-manager/commit/249c64def8feea112296e9e65b07b2de953d82e0) `onReady` callback from `layer` component was removed. This needs to be restored.

**Comment by andresgnlez** [comment]
PR fixing the issue: https://github.com/Vizzuality/layer-manager/pull/48

Anyway, I would like to continue the conversation because I don't feel layers themselves should have an `onLayerLoading` property exposed. I haven't found a real use case for this as it is the layer manager the one in charge of exposing when layers are "ready".

I would stand up for removing this `onLayerLoading` property (at least its use) and use `onReady`'s layer manager to know when layers are fetched.

Thoughts?

**Comment by mbarrenechea** [comment]
I think that you, as an app, wants to know when a layer is loading and when is ready. But they are different things. One thing is when the layer starts to load and another thing when it ### finishes.

The use case that comes to my mind would be, for example: 
you have a layer that takes a lot of time to load, you need to tell the user that something is happening right?

**Comment by edbrett** [comment]
@andresgnlez is this resolved? I think we have the layerLoading and onReady props behaving as they should?
