### ISSUE TITLE
Changing layers too fast results in duplicate layers on map

### ISSUE THREAD

**Issue by andresgnlez** [Vizzuality/layer-manager#54]
https://vizzuality.slack.com/files/UARH9UBPY/FL54Y7Q7K/seagrass_pete.mov

Apparently, layers with complex geometries take long to display and this is messing with other layers. That's a thought. I'm not even sure what's going on, but it could be related to the promise cancellation.

**Comment by edbrett** [comment]
#60 solves this issue
