### ISSUE TITLE
Error finally is not a function

### ISSUE THREAD

**Issue by davidsingal** [Vizzuality/layer-manager#56]
`TypeError: "Promise.all(...).then(...).finally is not a function"`

In happens in Firefox 68.0.1 64-bit. It is happening in all projects based on `create-react-app` (webpack, babel an react).

For the moment, I'm only got working using the next:
https://github.com/Vizzuality/gfw/blob/develop/app/javascript/app/index.js#L11

I open this issue in order to find the best solution to this problem.

**Comment by sorodrigo** [comment]
Maybe this is useful. If you want CRA to add polyfill https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md

**Comment by davidsingal** [comment]
I can confirm it works. Anyway, I don't understand why we need a polyfill when Firefox supports `finally` since 58 version.

**Comment by edbrett** [comment]
This is solved now. Thanks for a great time.
