### ISSUE TITLE
Abstract bitmapLayer and tileLayer to pull from deck.gl lib

### ISSUE THREAD

**Issue by edbrett** [Vizzuality/layer-manager#70]
We have copied and implemented our own version of these layers, and since then large updates have been made to them in the core lib. I propose:

1. we make a PR to deck.gl to fix the zoom issue we have with the TileLayer
2. we abstract the TileLayer to import from the deck.gl lib (possible now with a small hack
3. we make a PR for the BitMap layer to allow the passing of custom shaders and params to the GPU (easy peasy lemon squeezy 🍋 ).

**Comment by mbarrenechea** [comment]
Done
